# Auto-generated universe data — no external file needed on Streamlit Cloud
UNIVERSE_RECORDS = [
    {"sector": "Consulting and professional services", "sub_sector": "Legal & professional services", "ticker": "GTLY", "name": "Gateley (Holdings) plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Outsourcing / public services", "ticker": "CPI", "name": "Capita plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Pensions consulting", "ticker": "XPS", "name": "XPS Pensions Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Professional services / training", "ticker": "FDM", "name": "FDM Group (Holdings) plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Restructuring / advisory", "ticker": "BEG", "name": "Begbies Traynor Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Restructuring / advisory", "ticker": "FRP", "name": "FRP Advisory Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "HAYS", "name": "Hays plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "PAGE", "name": "PageGroup plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "RWA", "name": "Robert Walters plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "STEM", "name": "SThree plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Business process / public sector services", "ticker": "MMS", "name": "Maximus, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Business services", "ticker": "RGP", "name": "Resources Connection, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "HR consulting / executive search", "ticker": "KFY", "name": "Korn Ferry", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "HR outsourcing / PEO", "ticker": "NSP", "name": "Insperity, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "HR outsourcing / PEO", "ticker": "TNET", "name": "TriNet Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "IT & professional staffing", "ticker": "ASGN", "name": "ASGN Incorporated", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Management consulting", "ticker": "BAH", "name": "Booz Allen Hamilton Holding Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Management consulting", "ticker": "CRAI", "name": "CRA International, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Management consulting", "ticker": "FCN", "name": "FTI Consulting, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Management consulting", "ticker": "HURN", "name": "Huron Consulting Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Management consulting", "ticker": "ICFI", "name": "ICF International, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Payroll & HR services", "ticker": "ADP", "name": "Automatic Data Processing, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Payroll & HR services", "ticker": "PAYX", "name": "Paychex, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Professional services", "ticker": "CBZ", "name": "CBIZ, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Research & advisory", "ticker": "FORR", "name": "Forrester Research, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "BBSI", "name": "Barrett Business Services, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "KELYA", "name": "Kelly Services, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "KFRC", "name": "Kforce Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "MAN", "name": "ManpowerGroup Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Consulting and professional services", "sub_sector": "Staffing & recruiting", "ticker": "RHI", "name": "Robert Half Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "CSN", "name": "Chesnara plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "JUST", "name": "Just Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "LGEN", "name": "Legal & General Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "PHNX", "name": "Phoenix Group Holdings plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "PUK", "name": "Prudential plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Lloyd's / underwriting", "ticker": "HUW", "name": "Helios Underwriting plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Multi-line insurance", "ticker": "AV", "name": "Aviva plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "ADM", "name": "Admiral Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "DLG", "name": "Direct Line Insurance Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "SBRE", "name": "Sabre Insurance Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "BEZ", "name": "Beazley plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "HSX", "name": "Hiscox Ltd", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "LRE", "name": "Lancashire Holdings Limited", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Insurance services", "sub_sector": "Claims / TPA", "ticker": "CRD.A", "name": "Crawford & Company", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Claims / TPA", "ticker": "CRD.B", "name": "Crawford & Company", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Claims / TPA", "ticker": "CRVL", "name": "CorVel Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "CI", "name": "The Cigna Group", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "CNC", "name": "Centene Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "ELV", "name": "Elevance Health, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "HUM", "name": "Humana Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "MOH", "name": "Molina Healthcare, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "OSCR", "name": "Oscar Health, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Health insurance", "ticker": "UNH", "name": "UnitedHealth Group Incorporated", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "AJG", "name": "Arthur J. Gallagher & Co.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "AON", "name": "Aon plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "BRO", "name": "Brown & Brown, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "BRP", "name": "BRP Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "ERIE", "name": "Erie Indemnity Company", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "MMC", "name": "Marsh & McLennan Companies, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "RYAN", "name": "Ryan Specialty Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance brokerage", "ticker": "WTW", "name": "Willis Towers Watson Public Limited Company", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance distribution", "ticker": "EHTH", "name": "eHealth, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance distribution", "ticker": "GOCO", "name": "GoHealth, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance distribution", "ticker": "GSHD", "name": "Goosehead Insurance, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurance distribution", "ticker": "SLQT", "name": "SelectQuote, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurance distribution", "ticker": "TWFG", "name": "TWFG, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Insurtech", "ticker": "HIPO", "name": "Hippo Holdings Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurtech", "ticker": "LMND", "name": "Lemonade, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Insurtech", "ticker": "ROOT", "name": "Root, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "AFL", "name": "Aflac Incorporated", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "BHF", "name": "Brighthouse Financial, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "CNO", "name": "CNO Financial Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "FG", "name": "F&G Annuities & Life, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "GL", "name": "Globe Life Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "LNC", "name": "Lincoln National Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "MET", "name": "MetLife, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "MFC", "name": "Manulife Financial Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "PFG", "name": "Principal Financial Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "PRU", "name": "Prudential Financial, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "SLF", "name": "Sun Life Financial Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "UNM", "name": "Unum Group", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Life insurance", "ticker": "VOYA", "name": "Voya Financial, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Mortgage insurance", "ticker": "ESNT", "name": "Essent Group Ltd.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Mortgage insurance", "ticker": "MTG", "name": "MGIC Investment Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Mortgage insurance", "ticker": "NMIH", "name": "NMI Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Mortgage insurance", "ticker": "RDN", "name": "Radian Group Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "AFG", "name": "American Financial Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "AIG", "name": "American International Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "ALL", "name": "The Allstate Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "CB", "name": "Chubb Limited", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "CINF", "name": "Cincinnati Financial Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "HIG", "name": "The Hartford Financial Services Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "MKL", "name": "Markel Group Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "PGR", "name": "The Progressive Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "TRV", "name": "The Travelers Companies, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "P&C insurance", "ticker": "WRB", "name": "W. R. Berkley Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Reinsurance", "ticker": "AXS", "name": "AXIS Capital Holdings Limited", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Reinsurance", "ticker": "EG", "name": "Everest Group, Ltd.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Reinsurance", "ticker": "RNR", "name": "RenaissanceRe Holdings Ltd.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Reinsurance / specialty", "ticker": "ACGL", "name": "Arch Capital Group Ltd.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "AIZ", "name": "Assurant, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "KNSL", "name": "Kinsale Capital Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "ORI", "name": "Old Republic International Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "RLI", "name": "RLI Corp.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "SIGI", "name": "Selective Insurance Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "SKWD", "name": "Skyward Specialty Insurance Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Specialty insurance", "ticker": "TRUP", "name": "Trupanion, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Insurance services", "sub_sector": "Title insurance", "ticker": "FAF", "name": "Fidelity National Financial, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "B2B information / events / publishing", "ticker": "INF", "name": "Informa plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Compliance / professional information", "ticker": "WIL", "name": "Wilmington plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Credit / consumer data", "ticker": "EXPN", "name": "Experian plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Financial data / benchmark administration", "ticker": "LSEG", "name": "London Stock Exchange Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Identity / fraud data", "ticker": "GBG", "name": "GB Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Industry data / market intelligence", "ticker": "DATA", "name": "GlobalData Plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Public opinion / data analytics", "ticker": "YOU", "name": "YouGov plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Scientific / legal information", "ticker": "REL", "name": "RELX PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Information and data services", "sub_sector": "Business information", "ticker": "DNB", "name": "Dun & Bradstreet Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Credit / identity data", "ticker": "EFX", "name": "Equifax Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Credit data / scores", "ticker": "TRU", "name": "TransUnion", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Credit ratings & analytics", "ticker": "MCO", "name": "Moody's Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Exchange / market data", "ticker": "CBOE", "name": "Cboe Global Markets, Inc.", "listing_country": "US", "exchange": "Cboe BZX"},
    {"sector": "Information and data services", "sub_sector": "Financial data", "ticker": "FDS", "name": "FactSet Research Systems Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Financial data & analytics", "ticker": "SPGI", "name": "S&P Global Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "IP / academic / enterprise information", "ticker": "CLVT", "name": "Clarivate Plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Index / analytics", "ticker": "MSCI", "name": "MSCI Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Investment data", "ticker": "MORN", "name": "Morningstar, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Legal / tax / regulatory information", "ticker": "TRI", "name": "Thomson Reuters Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Market intelligence", "ticker": "MKTW", "name": "MarketWise, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Property / real estate data", "ticker": "CSGP", "name": "CoStar Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Risk / insurance data", "ticker": "VRSK", "name": "Verisk Analytics, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Scientific / legal information", "ticker": "RELX", "name": "RELX PLC", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Stock exchange / market data", "ticker": "CME", "name": "CME Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Stock exchange / market data", "ticker": "ICE", "name": "Intercontinental Exchange, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Information and data services", "sub_sector": "Stock exchange / market data", "ticker": "NDAQ", "name": "Nasdaq, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Information and data services", "sub_sector": "Valuation / workflow data", "ticker": "VALU", "name": "Value Line, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Cybersecurity / IT services", "ticker": "NCC", "name": "NCC Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "Digital services / software engineering", "ticker": "KNOS", "name": "Kainos Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "IT reseller / solutions", "ticker": "BYIT", "name": "Bytes Technology Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "IT reseller / solutions", "ticker": "CCC", "name": "Computacenter plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "IT reseller / solutions", "ticker": "SCT", "name": "Softcat plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "Managed network / cloud services", "ticker": "RCN", "name": "Redcentric plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "IT services", "sub_sector": "Analytics / digital ops", "ticker": "EXLS", "name": "ExlService Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Business process / outsourcing", "ticker": "CNXC", "name": "Concentrix Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Customer experience / outsourcing", "ticker": "TASK", "name": "TaskUs, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Customer experience BPO", "ticker": "IBEX", "name": "IBEX Limited", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Customer experience BPO", "ticker": "TTEC", "name": "TTEC Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Digital consulting", "ticker": "G", "name": "Genpact Limited", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Digital consulting", "ticker": "GLOB", "name": "Globant S.A.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Digital engineering", "ticker": "DAVA", "name": "Endava plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Digital engineering", "ticker": "EPAM", "name": "EPAM Systems, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Digital engineering", "ticker": "GDYN", "name": "Grid Dynamics Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Digital engineering", "ticker": "TWKS", "name": "Thoughtworks Holding, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Digital transformation / engineering", "ticker": "PSN", "name": "Parsons Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Enterprise services", "ticker": "VYX", "name": "NCR Voyix Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Fintech / investor communications tech", "ticker": "BR", "name": "Broadridge Financial Solutions, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Government IT services", "ticker": "CACI", "name": "CACI International Inc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Government IT services", "ticker": "LDOS", "name": "Leidos Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Government IT services", "ticker": "SAIC", "name": "Science Applications International Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "IT consulting", "ticker": "ACN", "name": "Accenture plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT reseller / services", "ticker": "PLUS", "name": "ePlus inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "IT reseller / solutions", "ticker": "CDW", "name": "CDW Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "CTSH", "name": "Cognizant Technology Solutions Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "DXC", "name": "DXC Technology Company", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "FIS", "name": "Fidelity National Information Services, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "GIB", "name": "CGI Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "IBM", "name": "International Business Machines Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "INFY", "name": "Infosys Limited", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "UIS", "name": "Unisys Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT services", "ticker": "WIT", "name": "Wipro Limited", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "IT solutions reseller", "ticker": "NSIT", "name": "Insight Enterprises, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Information services / analytics", "ticker": "NIQ", "name": "NIQ Global Intelligence plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "MSP / software management", "ticker": "NABL", "name": "N-able, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Managed infrastructure", "ticker": "KD", "name": "Kyndryl Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "IT services", "sub_sector": "Payments / financial software services", "ticker": "JKHY", "name": "Jack Henry & Associates, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "IT services", "sub_sector": "Research / advisory", "ticker": "IT", "name": "Gartner, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Platform / adviser admin", "ticker": "IHP", "name": "IntegraFin Holdings plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "ABDN", "name": "abrdn plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "JUP", "name": "Jupiter Fund Management plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "LIO", "name": "Liontrust Asset Management plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "POLR", "name": "Polar Capital Holdings plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "SDR", "name": "Schroders plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth / fiduciary services", "ticker": "JTC", "name": "JTC PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "AJB", "name": "AJ Bell plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "BRK", "name": "Brooks Macdonald Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "QLT", "name": "Quilter plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "RAT", "name": "Rathbones Group Plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "STJ", "name": "St. James's Place plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "TAM", "name": "Tatton Asset Management plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Advisory / investment banking", "ticker": "EVR", "name": "Evercore Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Advisory / investment banking", "ticker": "HLI", "name": "Houlihan Lokey, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Advisory / investment banking", "ticker": "LAZ", "name": "Lazard, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Advisory / investment banking", "ticker": "MC", "name": "Moelis & Company", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Advisory / investment banking", "ticker": "PJT", "name": "PJT Partners Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "ETF / digital wealth", "ticker": "WT", "name": "WisdomTree, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "AAMI", "name": "Acadian Asset Management Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "AMG", "name": "Affiliated Managers Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "APAM", "name": "Artisan Partners Asset Management Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "BEN", "name": "Franklin Resources, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "BLK", "name": "BlackRock, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "CNS", "name": "Cohen & Steers, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "FHI", "name": "Federated Hermes, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "JHG", "name": "Janus Henderson Group plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "TROW", "name": "T. Rowe Price Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Wealth management and advisory", "sub_sector": "Traditional asset management", "ticker": "VCTR", "name": "Victory Capital Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth / adviser platform", "ticker": "SEIC", "name": "SEI Investments Company", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "AMP", "name": "Ameriprise Financial, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "LPLA", "name": "LPL Financial Holdings Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "RJF", "name": "Raymond James Financial, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management", "ticker": "SF", "name": "Stifel Financial Corp.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Wealth management and advisory", "sub_sector": "Wealth management / brokerage", "ticker": "PIPR", "name": "Piper Sandler Companies", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Distribution / outsourcing", "ticker": "BNZL", "name": "Bunzl plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Supply chain services", "sub_sector": "Industrial / MRO distribution", "ticker": "RS1", "name": "RS Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Supply chain services", "sub_sector": "Specialized distribution", "ticker": "DPLM", "name": "Diploma PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Supply chain services", "sub_sector": "3PL / freight brokerage", "ticker": "CHRW", "name": "C.H. Robinson Worldwide, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Air freight / forwarding", "ticker": "FWRD", "name": "Forward Air Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Asset-light logistics", "ticker": "LSTR", "name": "Landstar System, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Asset-light logistics", "ticker": "RLGT", "name": "Radiant Logistics, Inc.", "listing_country": "US", "exchange": "NYSE American"},
    {"sector": "Supply chain services", "sub_sector": "Asset-light logistics", "ticker": "RXO", "name": "RXO, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Asset-light trucking / logistics", "ticker": "ULH", "name": "Universal Logistics Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Contract logistics", "ticker": "GXO", "name": "GXO Logistics, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Freight forwarding", "ticker": "EXPD", "name": "Expeditors International of Washington, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Industrial distribution / supply chain", "ticker": "FERG", "name": "Ferguson Enterprises Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Integrated freight & logistics", "ticker": "FDX", "name": "FedEx Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Integrated freight & logistics", "ticker": "UPS", "name": "United Parcel Service, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Intermodal / logistics", "ticker": "HUBG", "name": "Hub Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "LTL / logistics", "ticker": "ARCB", "name": "ArcBest Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "LTL transportation", "ticker": "ODFL", "name": "Old Dominion Freight Line, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "LTL transportation", "ticker": "SAIA", "name": "Saia, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Mail / shipping solutions", "ticker": "PBI", "name": "Pitney Bowes Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Transportation & logistics", "ticker": "JBHT", "name": "J.B. Hunt Transport Services, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Transportation / brokerage", "ticker": "XPO", "name": "XPO, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Truckload / logistics", "ticker": "CVLG", "name": "Covenant Logistics Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Truckload / logistics", "ticker": "KNX", "name": "Knight-Swift Transportation Holdings Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Truckload / logistics", "ticker": "MRTN", "name": "Marten Transport, Ltd.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Supply chain services", "sub_sector": "Truckload / logistics", "ticker": "SNDR", "name": "Schneider National, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Supply chain services", "sub_sector": "Truckload / logistics", "ticker": "WERN", "name": "Werner Enterprises, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Construction / engineering", "ticker": "COST", "name": "Costain Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering consulting", "ticker": "RCDO", "name": "Ricardo plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering services", "ticker": "BAB", "name": "Babcock International Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering services", "ticker": "KLR", "name": "Keller Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering services", "ticker": "RNWH", "name": "Renew Holdings plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering services", "ticker": "WG", "name": "John Wood Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Facilities / field services", "ticker": "MTO", "name": "Mitie Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Field services", "ticker": "MER", "name": "Mears Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Government / field services", "ticker": "SRP", "name": "Serco Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Steel / construction services", "ticker": "SFR", "name": "Severfield plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Testing, inspection & certification", "ticker": "ITRK", "name": "Intertek Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Building services", "ticker": "BLD", "name": "TopBuild Corp.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Civil engineering", "ticker": "GVA", "name": "Granite Construction Incorporated", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Electrical / building services", "ticker": "EME", "name": "EMCOR Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Electrical / industrial services", "ticker": "IESC", "name": "IES Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Electrical infrastructure services", "ticker": "MYRG", "name": "MYR Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "ACM", "name": "AECOM", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "BWMN", "name": "Bowman Consulting Group Ltd.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "J", "name": "Jacobs Solutions Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "NVEE", "name": "NV5 Global, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "STN", "name": "Stantec Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering & consulting", "ticker": "TTEK", "name": "Tetra Tech, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering / EPC", "ticker": "FLR", "name": "Fluor Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering / government services", "ticker": "KBR", "name": "KBR, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering / lifting services", "ticker": "AGX", "name": "Argan, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Engineering / power consulting", "ticker": "WLDN", "name": "Willdan Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Industrial / energy services", "ticker": "MTRX", "name": "Matrix Service Company", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Infrastructure / civil services", "ticker": "STRL", "name": "Sterling Infrastructure, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Infrastructure / utility services", "ticker": "MTZ", "name": "MasTec, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Infrastructure services", "ticker": "PRIM", "name": "Primoris Services Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Infrastructure services", "ticker": "PWR", "name": "Quanta Services, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Infrastructure services", "ticker": "ROAD", "name": "Construction Partners, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Marine / specialty construction", "ticker": "ORN", "name": "Orion Group Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Mechanical / HVAC services", "ticker": "FIX", "name": "Comfort Systems USA, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Offshore / field services", "ticker": "OII", "name": "Oceaneering International, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Safety / fire protection services", "ticker": "APG", "name": "APi Group Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Scientific / engineering consulting", "ticker": "EXPO", "name": "Exponent, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Telecom / utility field services", "ticker": "DY", "name": "Dycom Industries, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Field services, engineering services, and TIC", "sub_sector": "Testing, inspection & certification", "ticker": "ULS", "name": "UL Solutions Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Estate agency / lettings", "ticker": "BLV", "name": "Belvoir Group PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Estate agency franchising", "ticker": "TPFG", "name": "The Property Franchise Group PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Property portal", "ticker": "RMV", "name": "Rightmove plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Property services", "ticker": "LSL", "name": "LSL Property Services plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Real estate services", "ticker": "SVS", "name": "Savills plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "FOXT", "name": "Foxtons Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "WINK", "name": "M Winkworth plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Property services", "sub_sector": "Commercial brokerage", "ticker": "MMI", "name": "Marcus & Millichap, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Commercial real estate services", "ticker": "CIGI", "name": "Colliers International Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Commercial real estate services", "ticker": "CWK", "name": "Cushman & Wakefield plc", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Commercial real estate services", "ticker": "NMRK", "name": "Newmark Group, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Home transaction platform", "ticker": "OPAD", "name": "Offerpad Solutions Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Property management / residential services", "ticker": "FSV", "name": "FirstService Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Property services / mortgage tech", "ticker": "ASPS", "name": "Altisource Portfolio Solutions S.A.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Real estate services", "ticker": "CBRE", "name": "CBRE Group, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Real estate services", "ticker": "JLL", "name": "Jones Lang LaSalle Incorporated", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "COMP", "name": "Compass, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "DOUG", "name": "Douglas Elliman Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "EXPI", "name": "eXp World Holdings, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "FTHM", "name": "Fathom Holdings Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "REAX", "name": "The Real Brokerage Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Property services", "sub_sector": "Residential brokerage", "ticker": "RMAX", "name": "RE/MAX Holdings, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "Residential platform", "ticker": "BEKE", "name": "KE Holdings Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Property services", "sub_sector": "iBuying / residential platform", "ticker": "OPEN", "name": "Opendoor Technologies Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education / publishing", "ticker": "PSON", "name": "Pearson plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "MLVN", "name": "Malvern International plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Education", "sub_sector": "Education / media", "ticker": "GHC", "name": "Graham Holdings Company", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education / training", "ticker": "UTI", "name": "Universal Technical Institute, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education platform", "ticker": "CHGG", "name": "Chegg, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education platform", "ticker": "COUR", "name": "Coursera, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education platform", "ticker": "UDMY", "name": "Udemy, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "AFYA", "name": "Afya Limited", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "APEI", "name": "American Public Education, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "ATGE", "name": "Adtalem Global Education Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "DAO", "name": "Youdao, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "EDU", "name": "New Oriental Education & Technology Group Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "FC", "name": "Franklin Covey Co.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "GOTU", "name": "Gaotu Techedu Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "KLC", "name": "Kindercare Learning Companies, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "LAUR", "name": "Laureate Education, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "LINC", "name": "Lincoln Educational Services Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "LOPE", "name": "Grand Canyon Education, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "LRN", "name": "Stride, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "PRDO", "name": "Perdoceo Education Corporation", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "STRA", "name": "Strategic Education, Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Education", "sub_sector": "Education services", "ticker": "TAL", "name": "TAL Education Group", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "BPT", "name": "Bridgepoint Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "EMG", "name": "Man Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "ICG", "name": "ICG plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "III", "name": "3i Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "PHLL", "name": "Petershill Partners plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Emerging markets / alternatives", "ticker": "ASHM", "name": "Ashmore Group PLC", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Infrastructure / private assets", "ticker": "FSG", "name": "Foresight Group Holdings Limited", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Private equity investment company", "ticker": "HGT", "name": "HgCapital Trust plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Private equity investment company", "ticker": "HVPE", "name": "HarbourVest Global Private Equity Limited", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Private equity investment company", "ticker": "NBPE", "name": "NB Private Equity Partners Limited", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Private equity investment company", "ticker": "PNL", "name": "Pantheon International Plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Venture / alternatives", "ticker": "IPO", "name": "IP Group plc", "listing_country": "UK", "exchange": "LSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative / resource manager", "ticker": "SII", "name": "Sprott Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "APO", "name": "Apollo Global Management, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "ARES", "name": "Ares Management Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "BAM", "name": "Brookfield Asset Management Ltd.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "BN", "name": "Brookfield Corporation", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "BX", "name": "Blackstone Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "CG", "name": "The Carlyle Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "GCMG", "name": "GCM Grosvenor Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "HLNE", "name": "Hamilton Lane Incorporated", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "KKR", "name": "KKR & Co. Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "OWL", "name": "Blue Owl Capital Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "P10", "name": "P10, Inc.", "listing_country": "US", "exchange": "NYSE"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "PAX", "name": "Patria Investments Limited", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "STEP", "name": "StepStone Group Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Alternative asset manager", "ticker": "TPG", "name": "TPG Inc.", "listing_country": "US", "exchange": "NASDAQ"},
    {"sector": "Alternative asset management", "sub_sector": "Litigation finance / alternatives", "ticker": "BUR", "name": "Burford Capital Limited", "listing_country": "US", "exchange": "NYSE"}
]
